on:
  push:
  schedule:
    - cron: '0 0 * * *'
    
jobs:
  publish:
    runs-on: ubuntu-latest
      
    name: Build Chrome OS releases database
    steps:
      - name: download repo
        uses: actions/checkout@v4
      
      - name: cache downloads
        uses: actions/cache@v4
        with:
          path: downloads
          key: downloads-${{ github.ref }}-${{ github.run_id }}
          restore-keys: |
            downloads-${{ github.ref }}
      
      - name: install deps
        run: |
          set -x
          sudo apt-get update
          sudo apt-get install -y vboot-kernel-utils busybox binwalk pcregrep
          python3 -m venv .venv
          source .venv/bin/activate
          pip3 install -e .

      - name: run build
        run: |
          set -x
          source .venv/bin/activate
          python3 -m cros_releases --commit

      - name: upload database as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: data
          path: data/repo/data.json
          compression-level: 9
      
      - name: upload downloads as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: downloads
          path: downloads/
          compression-level: 9

  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1