on:
  push:
  schedule:
    - cron: '0 0 * * 0'
    
jobs:
  publish:
    runs-on: ubuntu-latest
      
    name: Build Chrome OS releases database
    steps:
      - name: download repo
        uses: actions/checkout@v4

      - name: restore downloads cache
        uses: actions/cache/restore@v4
        with:
          path: downloads
          key: downloads-${{ github.ref }}
      
      - name: run build
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip3 install -r requirements.txt
          python3 main.py

      - name: upload database as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: data
          path: data/data.json
          compression-level: 9
      
      - name: upload downloads as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: downloads
          path: downloads/
          compression-level: 9
      
      - name: save downloads cache
        uses: actions/cache/save@v4
        with:
          path: downloads
          key: downloads-${{ github.ref }}

      - name: publish database
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "<>"
          cd data
          git clone "https://${{ secrets.GH_TOKEN }}@github.com/MercuryWorkshop/chromeos-releases-data" -b main
          cd chromeos-releases-data
          cp ../data.json ./
          git add .
          git commit -m "update data.json"
          git push origin main