on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  publish:
    runs-on: ubuntu-latest
      
    name: Trigger Internet Archive snapshots
    steps:
      - name: download repo
        uses: actions/checkout@v4
      
      - name: trigger archives
        run: |
          env TOKEN="${{ secrets.IA_API_KEY }}" ./cron_archive.sh

  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1